using System;
using System.Collections.Generic;
using Network.API.Models;
using Network.API.Services;
using TMPro;
using UI;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace Managers.UIManager
{
    public class CreateRoomSceneManager : MonoBehaviour
    {
        private const string WaitRoomSceneName = "WaitRoom";
        private const string MainMenuSceneName = "MainMenu";

        [Header("References")]
        [SerializeField] private TMP_InputField roomNameInput;
        [SerializeField] private TextMeshProUGUI roomCodeHintText;
        [SerializeField] private Button createRoomButton;
        [SerializeField] private Button publicButton;
        [SerializeField] private Button privateButton;
        [SerializeField] private Button maxPlayersButtonA;
        [SerializeField] private Button maxPlayersButtonB;
        [SerializeField] private Button maxPlayersButtonC;
        [SerializeField] private Button backButton;

        [Header("State")]
        [SerializeField] private Color activeColor = new(0.92f, 0.42f, 0.19f, 1f);
        [SerializeField] private Color inactiveColor = new(1f, 1f, 1f, 0.2f);

        private readonly int[] _maxPlayerOptions = { 2, 4, 6 };
        private Button[] _maxPlayerButtons;
        private bool _isSubmitting;
        private bool _isPublic = true;
        private int _selectedMaxPlayers = 4;

        private void Awake()
        {
            EnsureInputModule();
            AutoBind();
            SeedDefaults();
            ApplyMaxPlayerLabels();
            ApplySelectionVisuals();
        }

        private void OnEnable()
        {
            BindButtons();
        }

        private void OnDisable()
        {
            UnbindButtons();
        }

        private void SeedDefaults()
        {
            var gameManager = GameManager.EnsureInstance();
            if (roomNameInput != null && string.IsNullOrWhiteSpace(roomNameInput.text))
            {
                var username = gameManager.Player?.Username;
                roomNameInput.text = string.IsNullOrWhiteSpace(username) ? "My Room" : $"{username}'s room";
            }

            if (roomCodeHintText != null)
                roomCodeHintText.text = "Auto-generated by server";
        }

        private void BindButtons()
        {
            createRoomButton?.onClick.AddListener(HandleCreateRoomClicked);
            publicButton?.onClick.AddListener(HandlePublicClicked);
            privateButton?.onClick.AddListener(HandlePrivateClicked);
            backButton?.onClick.AddListener(HandleBackClicked);
            maxPlayersButtonA?.onClick.AddListener(HandleMaxPlayersAClicked);
            maxPlayersButtonB?.onClick.AddListener(HandleMaxPlayersBClicked);
            maxPlayersButtonC?.onClick.AddListener(HandleMaxPlayersCClicked);
        }

        private void UnbindButtons()
        {
            createRoomButton?.onClick.RemoveListener(HandleCreateRoomClicked);
            publicButton?.onClick.RemoveListener(HandlePublicClicked);
            privateButton?.onClick.RemoveListener(HandlePrivateClicked);
            backButton?.onClick.RemoveListener(HandleBackClicked);
            maxPlayersButtonA?.onClick.RemoveListener(HandleMaxPlayersAClicked);
            maxPlayersButtonB?.onClick.RemoveListener(HandleMaxPlayersBClicked);
            maxPlayersButtonC?.onClick.RemoveListener(HandleMaxPlayersCClicked);
        }

        private async void HandleCreateRoomClicked()
        {
            if (_isSubmitting)
                return;

            var gameManager = GameManager.EnsureInstance();
            if (!gameManager.IsAuthenticated)
            {
                UniversalPopup.ShowError("Please log in before creating a room.");
                return;
            }

            _isSubmitting = true;
            try
            {
                var requestedRoomName = roomNameInput != null ? roomNameInput.text.Trim() : string.Empty;
                var request = new CreateRoomDto
                {
                    MaxPlayers = _selectedMaxPlayers,
                    IsPublic = _isPublic,
                    CardSetIds = new List<string>()
                };

                var response = await RoomService.Instance.CreateRoomAsync(request, gameManager.AccessToken);
                if (response?.success != true || response.data == null)
                {
                    if (response != null && response.errorCode == "PLAYER_ALREADY_IN_ROOM" && response.details != null)
                    {
                        var oldRoomId = response.details.Value<string>("roomId");
                        if (!string.IsNullOrWhiteSpace(oldRoomId))
                        {
                            UniversalPopup.ShowInfo("Bạn đang ở trong phòng khác. Đang rời phòng cũ để tạo lại...");
                            try
                            {
                                await Network.Websocket.AppRoomWebsocketClient.ForceLeaveRoomAsync(gameManager.AccessToken, oldRoomId);
                                RoomManager.EnsureInstance().ClearCurrentRoom();
                                
                                // Retry creation
                                response = await RoomService.Instance.CreateRoomAsync(request, gameManager.AccessToken);
                            }
                            catch (Exception wsEx)
                            {
                                Debug.LogWarning($"[CreateRoom] Failed to auto-leave old room {oldRoomId}: {wsEx.Message}");
                            }
                        }
                    }
                }

                if (response?.success != true || response.data == null)
                {
                    UniversalPopup.ShowError(string.IsNullOrWhiteSpace(response?.message)
                        ? "Unable to create room."
                        : response.message);
                    return;
                }

                var roomManager = RoomManager.EnsureInstance();
                roomManager.SetCurrentRoom(response.data, requestedRoomName);

                if (roomCodeHintText != null)
                    roomCodeHintText.text = response.data.Code ?? "Created";

                UniversalPopup.ShowSuccess("Room created.");
                LoadWaitRoom();
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[CreateRoom] Create room failed: {ex.Message}");
                UniversalPopup.ShowError("Unable to create room.");
            }
            finally
            {
                _isSubmitting = false;
            }
        }

        private void HandlePublicClicked()
        {
            _isPublic = true;
            ApplySelectionVisuals();
        }

        private void HandlePrivateClicked()
        {
            _isPublic = false;
            ApplySelectionVisuals();
        }

        private void HandleMaxPlayersClicked(int index)
        {
            if (index < 0 || index >= _maxPlayerOptions.Length)
                return;

            _selectedMaxPlayers = _maxPlayerOptions[index];
            ApplySelectionVisuals();
        }

        private void HandleMaxPlayersAClicked() => HandleMaxPlayersClicked(0);
        private void HandleMaxPlayersBClicked() => HandleMaxPlayersClicked(1);
        private void HandleMaxPlayersCClicked() => HandleMaxPlayersClicked(2);

        private void HandleBackClicked()
        {
            LoadMainMenu();
        }

        private void ApplyMaxPlayerLabels()
        {
            _maxPlayerButtons = new[] { maxPlayersButtonA, maxPlayersButtonB, maxPlayersButtonC };
            for (var i = 0; i < _maxPlayerOptions.Length && i < _maxPlayerButtons.Length; i++)
            {
                var label = _maxPlayerButtons[i] != null
                    ? _maxPlayerButtons[i].GetComponentInChildren<TextMeshProUGUI>(true)
                    : null;
                if (label != null)
                    label.text = _maxPlayerOptions[i].ToString();
            }
        }

        private void ApplySelectionVisuals()
        {
            SetButtonColor(publicButton, _isPublic);
            SetButtonColor(privateButton, !_isPublic);

            if (_maxPlayerButtons == null)
                return;

            for (var i = 0; i < _maxPlayerButtons.Length && i < _maxPlayerOptions.Length; i++)
                SetButtonColor(_maxPlayerButtons[i], _selectedMaxPlayers == _maxPlayerOptions[i]);
        }

        private void SetButtonColor(Button button, bool active)
        {
            var image = button != null ? button.GetComponent<Image>() : null;
            if (image != null)
                image.color = active ? activeColor : inactiveColor;
        }

        private void AutoBind()
        {
            roomNameInput ??= FindByPath("Canvas/EnterCode View/RoomNameTextBox/InputField (TMP)")?.GetComponent<TMP_InputField>();
            roomCodeHintText ??= FindByPath("Canvas/EnterCode View/EnterCodeTextBox/Code")?.GetComponent<TextMeshProUGUI>();
            createRoomButton ??= FindByPath("Canvas/EnterCode View/Join Button")?.GetComponent<Button>();
            publicButton ??= FindByPath("Canvas/EnterCode View/PublicButton")?.GetComponent<Button>();
            privateButton ??= FindByPath("Canvas/EnterCode View/PrivateButton")?.GetComponent<Button>();
            maxPlayersButtonA ??= FindByPath("Canvas/EnterCode View/MaxPlayerPanel/MaxPlayerButton")?.GetComponent<Button>();
            maxPlayersButtonB ??= FindByPath("Canvas/EnterCode View/MaxPlayerPanel/MaxPlayerButton (1)")?.GetComponent<Button>();
            maxPlayersButtonC ??= FindByPath("Canvas/EnterCode View/MaxPlayerPanel/MaxPlayerButton (2)")?.GetComponent<Button>();
            backButton ??= FindByPath("Canvas/BackButton")?.GetComponent<Button>();
        }

        private Transform FindByPath(string path)
        {
            var roots = gameObject.scene.GetRootGameObjects();
            foreach (var root in roots)
            {
                var result = FindByPath(root.transform, path);
                if (result != null)
                    return result;
            }

            return null;
        }

        private static Transform FindByPath(Transform current, string path)
        {
            if (current == null)
                return null;

            var currentPath = current.name;
            var parent = current.parent;
            while (parent != null)
            {
                currentPath = $"{parent.name}/{currentPath}";
                parent = parent.parent;
            }

            if (string.Equals(currentPath, path, StringComparison.Ordinal))
                return current;

            foreach (Transform child in current)
            {
                var result = FindByPath(child, path);
                if (result != null)
                    return result;
            }

            return null;
        }

        private static void LoadWaitRoom()
        {
            if (NavigationManager.Instance != null)
            {
                NavigationManager.Instance.LoadWaitRoom();
                return;
            }

            SceneManager.LoadScene(WaitRoomSceneName);
        }

        private static void LoadMainMenu()
        {
            if (NavigationManager.Instance != null)
            {
                NavigationManager.Instance.LoadMainMenu();
                return;
            }

            SceneManager.LoadScene(MainMenuSceneName);
        }

        private void EnsureInputModule()
        {
            var eventSystem = FindFirstObjectByType<UnityEngine.EventSystems.EventSystem>();
            if (eventSystem != null)
            {
                var legacyInput = eventSystem.GetComponent<UnityEngine.EventSystems.StandaloneInputModule>();
                if (legacyInput != null)
                {
                    DestroyImmediate(legacyInput);
                    eventSystem.gameObject.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();
                    Debug.Log($"[InputHelper] Successfully upgraded EventSystem in scene {gameObject.scene.name} to InputSystemUIInputModule.");
                }
            }
        }
    }
}
