### 1. Test Case: Register Guest (Success) - Expected 200 OK
# @name loginGuest
POST {{host}}/api/v1/auth/guest
Content-Type: application/json

{
  "deviceId": "{{deviceId}}"
}

> {%
    client.test("API returns successful 200 OK", function() {
        client.assert(response.status === 200, "Error: status code is not 200");
    });
    client.test("Check DTO response format", function() {
        client.assert(response.body.data.hasOwnProperty("user"), "Missing user in JSON response");
        client.assert(response.body.data.hasOwnProperty("accessToken"), "Missing accessToken in JSON response");
        client.global.set("accessToken", response.body.data.accessToken);
    });
%}


### 2. Test Case: Missing DeviceId (Bad Request) - Expected 400 Bad Request
POST {{host}}/api/v1/auth/guest
Content-Type: application/json

{
  "deviceId": ""
}

> {%
    client.test("Server blocks empty deviceId with 400", function() {
        client.assert(response.status === 400, "Should have failed due to empty deviceId!");
    });
%}

### 3. Test Case: Invalid Google Token (Unauthorized) - Expected 401 Unauthorized
POST {{host}}/api/v1/auth/google
Content-Type: application/json

{
  "idToken": "invalid-token-blah-blah"
}

> {%
    client.test("Server blocks invalid google token", function() {
        client.assert(response.status === 401, "Should have failed with 401!");
    });
%}
